### ISSUE TITLE
SCM-TFVC: Annotate is performed file by file, even though without violation

### ISSUE THREAD

**Issue by SebastienLorrain** [lg2de/sonar-scm-tfvc#59]
When active, the plugin seems to annotate all files one by one, which can be seen in a profusion of requests in Fiddler. It seems to concern every file, not only those where violations were detected.

For a consequent project of more than 1000 files (with only 5 where violations actually occur), it runs for more than 1h of non-stop annotation.

Is it expected to remain that way or is there an optimisation in the works?

**Comment by lg2de** [comment]
Sorry for strong delay for my comment...

I've taken responsibility for the repository when it had not maintainer anymore. So, I'm not sure in all details because I'm not the original developer.
According to my understanding there is no optimization possible on plugin side. It implements an interface of the SonarQube analyzer. The plugin is requested to provide annotation information on request of the analyzer/server.

We are analyzing several large projects with 2000 or 3000 files for many year. We did not face any issue so far.

**Comment by SebastienLorrain** [comment]
Hello Lukas,

Thanks for the answer ;)

The configuration in question in my case was a TFS server on another
continent, a code base of more than 40000 files.
The annotation of files one by one, would amount to a total of 3 to 4 hours
(just for annotation)

But hopefully, the code in the plugin is optimized so that files that are
not modified are not annotated again, which mildens the problem for
subsequent analyses.

Not sure anything can be done indeed about TFS, probably a limitation in
their API.

Best regards,

**Comment by lg2de** [comment]
I realized that first time analysis takes very long time. But subsequent analysis sessions are even faster.
I guess the analyzer invoking the plugin API performs any kind of optimization!?

Is it ok to close this issue? At least at the moment I do not have any idea for such optimization within the plugin.
It would also be possible to mark this as "enhancement". Maybe someone else has an idea.

**Comment by SebastienLorrain** [comment]
Sure, you can close

Thanks for answering!
