### ISSUE TITLE
SCM-TFVC: Unable to annotate the project. Exception: 'TF30063: You are not authorized to access https://devops.xyz.com/abc/.'

### ISSUE THREAD

**Issue by azharbroadpeak** [lg2de/sonar-scm-tfvc#68]
Hi TFVC team,
I am facing the above issue. Annotation was working just fine with-out any issue and then all of sudden it started failing for all projects. 

Here is the Error Message :**SCM-TFVC: Unable to annotate the project. Exception: 'TF30063: You are not authorized to access https://devops.xyz.com/abc/.'**
here is the version of sonarquebe that we are using.
![image](https://user-images.githubusercontent.com/48979387/129080573-118939da-aca2-4742-975f-955631b4e223.png)
TFVC SCM Provider for SonarQube | 2.3.1 (build 115)installed

![image](https://user-images.githubusercontent.com/48979387/129080988-72b0088c-575e-4ee4-9e59-271b04904dcd.png)

![image](https://user-images.githubusercontent.com/48979387/129079694-a746a709-736b-4d3f-add4-d31b138ede69.png)

Log file is attached.
[log_8_14777.zip](https://github.com/lg2de/sonar-scm-tfvc/files/6970465/log_8_14777.zip)

**Comment by azharbroadpeak** [comment]
Hi team,
Please help out in above issue.

**Comment by azharbroadpeak** [comment]
It seems tfvc plugin team is no more alive.:(

**Comment by lg2de** [comment]
Please note that we are in holiday season...

I'm not sure, what kind of authorization you are using.
If TFS reports an authentication issue, maybe there is an authentication issue?
Please check if the user or its token is still valid.

**Comment by azharbroadpeak** [comment]
We are using Azure Active directory for authentication. Every thing was fine and then this issue came up suddenly.

**Comment by lg2de** [comment]
"came up suddenly" means: No change of plugin or its configuration?
Then it sounds even more like a change of DevOps behavior or its configuration.

**Comment by azharbroadpeak** [comment]
Yes annotation was working fine with above mentioned tfvc plugin and version of SonarQube with all our DevOps build agents servers and related collections. But then above error start appearing for all governance pipelines. But no issues with Azure git repos. With azure git repos annotation is working fine no such authentication issue is appearing we are using same service connection and  same global token for all projects git repos and tfvc both use same token.

**Comment by lg2de** [comment]
But git and TFVC are not the same, also not in authorization in DevOps.

This plugin just uses the DevOps API to access the TFVC data.
If this API throws the mentioned failure, this is maybe not an issue for the plugin.

Unfortunately I cannot help if the problem is not reproducible to me.
For me it is working fine.
Please help to identify what was changed.

**Comment by azharbroadpeak** [comment]
Thanks,  I will get back if I get something.

**Comment by HipDragon** [comment]
@lg2de I just configured a new SonarQube server version 9.2.3 (build 50713), and installed this plugin to get the blame information. We are using TFVC from the Azure service, and are getting the same error message listed here. I have tried to use a token with full administrator rights with no success configured in the SonarQube server.

Our Azure DevOps TF setup has two repositories under it, not sure if that is causing an issue. Also is there a way to test the required connection first without running the full pipeline? It might help pin point the issue faster.

Any help to get thing working would be great, also looking for what is the minimum token permissions to get this working as well.

**Comment by lg2de** [comment]
Sorry for the strong delay.
So far I never used DevOps Services, so I had no experience.

Today I used my enterprise account to setup testing services instance.
Here it is working as expected (running fine with DevOps Server).

According to my experiance the following privileges are required for the PAT:
* Code (Full)
* Identity (Read & manage)

**Comment by lg2de** [comment]
If you want to test without the pipeline, then you can use the embedded EXE directly.
I've changed the build script to provide the EXE as separate EXE.
Please have a look on https://ci.appveyor.com/project/lg2de/sonar-scm-tfvc/builds/42346364/artifacts

**Comment by HipDragon** [comment]
Sorry for the delay in getting back to you, I downloaded the executable. Then ran it, which helps get the error messages much faster that running the pipelines to generate the errors.

Unfortunately I'm still getting the error "TF30063: You are not authorized to access <Collection UI>". Even after making sure my PAT has the privileges you indicated. 

Is there anything else I can do to find the issue and correct it? Under the DefaultCollection we show two different projects with repositories, not sure if that has anything to do with it.

**Comment by lg2de** [comment]
:(

If you are familiar with C# you can fetch the solution and debug the application: https://github.com/lg2de/sonar-scm-tfvc/blob/master/SonarTfsAnnotate.sln

Further, please make sure that the PAT is created on collection level. This is the entry point used the application.
Can you share some more details?

**Comment by HipDragon** [comment]
So I downloaded and tried to sort out the issues I'm seeing. After changing the authentication type to ["Visual Studio sign-in prompt (Microsoft Account or Azure Active Directory backed) for SOAP services"](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/soapsamples?view=azure-devops) I can get it to work. Because that worked the issues is with my PAT. I'm still lost as to why that's an issue, as I have followed Microsoft's guide on how to create a PAT, gave it full permissions and still it says not authenticated.

I'm trying to find a Microsoft contact to help figure it out. Thanks for you're help.

**Comment by HipDragon** [comment]
Update, I was able to build the project and figured out the PAT access with the project SonarTfsAnnotate. So locally I can get it to ask to annotate files and that is working correctly in the project. 

However I'm still getting the error message on the pipeline, I have updated the PAT and URI to make sure it matches what I tested in SonarTfsAnnotate. I have also updated the plugin to version 2.4, I have the PAT defined in SonarQube and not in the pipeline. Is there any troubleshooting tips you @lg2de  have to figure out what is going on?

**Comment by lg2de** [comment]
I do not have troubleshooting tips because I do not have experience with different systems.

If you get correct result with SonarTfsAnnotate.exe and failure in the pipeline, it should be related to the configuration.
Recently I have made the experience that you must not provide username or password when using the PAT.
Please check your configuration. Maybe you can share some screenshots.

**Comment by HipDragon** [comment]
Below is the screenshot of the tfvc configuration screen, as you can see no username or password is entered there. I put the PAT value into the pipeline directly and it works, which leads me to believe it's not going from SonarQube to Azure pipelines correctly. Any way to see what is being passed into the pipeline from SonarQube? I can also directly access the SonarQube database, and noticed the value I put in matches the value I expect.

![image](https://user-images.githubusercontent.com/23106295/171206823-42a1d707-f997-497f-919d-d321545be24e.png)

**Comment by lg2de** [comment]
I've added some more debug output to the annotate exe.
Please check the testing artifact from PR #70.
Hope we get further details. Please share the pipeline log, as detailed as possible.

**Comment by HipDragon** [comment]
Sorry it took so long to get this going. 

I have more details, there is a file called SonarQubeAnalysisConfig.xml that is created in the pipeline _work folder, for this run it was _work/4/.sonarqube/config, it contains an xml tag ServerSettings that list all the settings passed from SonarQube to the pipeline during the Prepare analysis on SonarQube step. There is this tag <Property Name="sonar.tfvc.collectionuri">, but no matching PAT tag is created when the PAT is configured on SonarQube.

I believe that the missing tag is what is causing the issue.

Waiting for the logs to post that will also confirm that the PAT was not used from SonarQube.

**Comment by lg2de** [comment]
I've revised the PR #70 because you are right, the new debugging information was not visible.
Now you should see output like this:

12:33:44.858 DEBUG: SCM-TFVC: Executing the TFVC annotate command: c:\buid\_work\525\.sonarqube\out\.sonar\.sonartmp\SonarTfsAnnotate9815944869301069612.exe
12:33:47.749 DEBUG: SCM-TFVC: received output: <Enter your credentials - username, password, PAT (three separate rows):>
12:33:47.749 DEBUG: SCM-TFVC: received output: <**Connecting using default credentials...**>
12:33:47.749 DEBUG: SCM-TFVC: received output: <Enter the Collection URI:>
12:33:48.671 DEBUG: SCM-TFVC: received output: <Enter the paths to annotate:>
12:33:48.671 INFO: SCM-TFVC: annotating C:/buid/_work/525/s/***/EnumerableExtensions.cs

**Comment by nhvduy** [comment]
Hello @lg2de 
I am happy when I found your extension, @lg2de. 
I am using TFS 2018 and my source code is in TFVC. I downloaded latest version 2.4.0 of SCM TFVC extension. I noticed that the extension sometimes does not work as expected. Sometimes I got the error message "TF30063: You are not authorized to access https://devops.xyz.com/abc/". There is nothing changes in the configuration as well as the build agent.

**Comment by lg2de** [comment]
@nhvduy can you please share more details as mentioned above?
Please note that this issue is already closed.
Please note that I can only help issues which are reproducible.

**Comment by nhvduy** [comment]
Thanks @lg2de for your response. I am not sure how the issue is reproduced.
I use TFS 2018 and our code repository is in TFVC and the enterprise sonar license. I downloaded the latest SCM TFVC extension version. The build agent is not changed, but sometime I got error of Unauthorized to TFVC. 
Here is the logs:

17:05:07.020 INFO: SCM Publisher SCM provider for this project is: tfvc
17:05:07.020 INFO: SCM Publisher 1360 source files to be analyzed
17:05:07.020 DEBUG: SCM-TFVC: Executing the TFVC annotate command: C:\Agent\_work\24\s\.scannerwork\.sonartmp\SonarTfsAnnotate9401153066551269165.exe
17:05:08.082 DEBUG: SCM-TFVC: received output: <Enter your credentials>
17:05:08.082 DEBUG: SCM-TFVC: received output: <Enter the Collection URI>
##[error]17:05:11.114 ERROR: SCM-TFVC: Unable to annotate the project. Exception: 'TF30063: You are not authorized to access https://abc.com/tfs/DefaultCollection/.'.
##[debug]Processed: ##vso[task.logissue type=error;]17:05:11.114 ERROR: SCM-TFVC: Unable to annotate the project. Exception: 'TF30063: You are not authorized to access https://abc.com/tfs/DefaultCollection/.'.
17:05:11.114 ERROR: SCM-TFVC: Unable to annotate the project. Exception: 'TF30063: You are not authorized to access https://abc.com/tfs/DefaultCollection/.'.
17:05:11.114 INFO: SCM Publisher 0/1360 source files have been analyzed (done) | time=4094ms
17:05:11.114 WARN: Missing blame information for the following files:
17:05:11.114 WARN:   * Stored Procedures/spa_sdciaodicn.sql
17:05:11.114 WARN:   * Tables/abcdad.sql

**Comment by lg2de** [comment]
> ... but sometime I got error of Unauthorized to TFVC

This is nothing what I can debug or fix.
If the problem is transient I do not have any idea.

**Comment by mikegscr** [comment]
Hi everyone! 
I am also having the same problem. What I have noticed from the debug information is that the scanner is adding a dot to the end of the URL (that's how it stays in the Azure Pipeline log) , when clicking on the URL, it gets the same error (You are not authorized to access) and it is because this "dot" modifies the name of the project. 

Hope this helps to find the cause of the problem!
I'm using Sonarqube 9.5.0.56709 and SCM-TFVC 2.4.0  on DevOps Services

**Comment by nhvduy** [comment]
Hello @mikegscr 
Did you resolve the issue? How could you remove the extra "." at the end of the URL?

**Comment by lg2de** [comment]
Please share the debug log, or at least the relevant part.
Then I can check if the additional "dot" comes from the plugin.
Maybe it is only a problem in the visualization, the kind of creating log output.

**Comment by mikegscr** [comment]
> Please share the debug log, or at least the relevant part. Then I can check if the additional "dot" comes from the plugin. Maybe it is only a problem in the visualization, the kind of creating log output.

Hi @lg2de , here is the log section where the URL have this extra dot 
![image](https://user-images.githubusercontent.com/79493045/204920323-ef20811d-b1cc-4309-b306-004e5c7ce45a.png)

When i try to open that url it fails in azure devops because of the "dot" 
![image](https://user-images.githubusercontent.com/79493045/204920546-0f2879de-05c4-4069-9707-dc97d46c85a7.png)

Tell me if you need more information

PS: @nhvduy , no, I have not found a workaround for this issue

**Comment by Stelyi** [comment]
Any updates on this one? I also have the 'dot' issue...

**Comment by lg2de** [comment]
The "dot" at the end of the message is generated by Microsoft code.
You can find it also in other contexts.

Because I cannot reproduce the issue (DevOps Server and DevOps Services) I cannot help. Please try deep analysis with the source code. If you find the bug causing the issue for you, a bugfix PR is welcome.

**Comment by mikegscr** [comment]
Hola a todos! respondo en español para poder ser claro.
Aplicando los siguientes pasos, el problema desapareció:
1. Habilité la siguiente opción en el "Agent Job":
![image](https://user-images.githubusercontent.com/79493045/231267192-a07f5f28-b1de-4535-b151-5dddbde6d591.png)
2. En el task "Prepare Analysis Configuration" agregué la siguiente opción:
**_sonar.tfvc.pat.secured=$(System.AccessToken)_**

Utilizo la versión 2.4.0 del scanner, en versiones previas no requería dicha configuración para que funcionara correctamente el scanner. 
Espero les ayude a los que aún tienen el problema

Saludos!

**Comment by nhvduy** [comment]
Thanks @mikegscr It works on my side. Awesome!
